language: ruby
rvm:
  - "1.9.3"
after_script:
- bundle_cache

notifications:
  recipients:
    - melsatar@gmail.com

script: 
 - RAILS_ENV=test bundle exec rake db:migrate --trace
 - bundle exec rake db:test:prepare
 - bundle exec cucumber

