language: ruby
rvm:
  - "1.9.3"
notifications:
  recipients:
    - melsatar@gmail.com

script: 
 - RAILS_ENV=test bundle exec rake --trace db:migrate
 - bundle exec rake db:test:prepare
 - bundle exec cucumber

